/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package counsellorapp;
import java.util.*;
 
/**
 *
 * @author sohumsanjaythadani
 */
public class Calculator extends javax.swing.JFrame {
    String activityMainSelect;
    String activitySubSelect;
    storagelist listC = new storagelist();
    String printed;
    double hourSummation;
   

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CalculateM = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 40)); // NOI18N
        jLabel1.setText("Click Calculate");

        CalculateM.setText("Calculate");
        CalculateM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(CalculateM)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(CalculateM)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CalculateMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateMActionPerformed
        hourSummation = listC.calculateactivitymainSum(activityMainSelect);
        printed = " " + hourSummation;
        jLabel1.setText(printed);
    }//GEN-LAST:event_CalculateMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }
    
    public void run(){
   
    }
    
    public String setactivityMainSelect(String activityMain){
        activityMainSelect = activityMain;
        return activityMainSelect;
    }
    
    public String setactivitySubSelect(String activitySub){
        activitySubSelect = activitySub;
        return activitySub;
    }
    
    public void passList(storagelist list){
        this.listC = list;
    }
    
    public storagelist set_listCopy(storagelist list){
        this.listC= list;
        return listC;
    }
      
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CalculateM;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
