/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package counsellorapp;

/**
 *
 * @author sohumsanjaythadani
 */
public class DirectStudentServices extends javax.swing.JFrame {
    
    String activityMain = "Direct Student Services";
    String activitySub;

    /**
     * Creates new form DirectStudentServices
     */
    public DirectStudentServices() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        IndividualCounsel = new javax.swing.JRadioButton();
        SmallGroupCounsel = new javax.swing.JRadioButton();
        ClassInstruct = new javax.swing.JRadioButton();
        IndividualStudentAdvising = new javax.swing.JRadioButton();
        ChildProtect = new javax.swing.JRadioButton();
        TestInterpret = new javax.swing.JRadioButton();
        NewStudentOrient = new javax.swing.JRadioButton();
        ParentTeacherMeetings = new javax.swing.JRadioButton();
        Stopwatch = new javax.swing.JButton();
        CalculateMainActivityGroup = new javax.swing.JButton();
        CalculateSubActivityGroup = new javax.swing.JButton();
        Closewindow = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        IndividualCounsel.setText("Individual Counseling ");
        IndividualCounsel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IndividualCounselActionPerformed(evt);
            }
        });

        SmallGroupCounsel.setText("Small Group Counseling");
        SmallGroupCounsel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SmallGroupCounselActionPerformed(evt);
            }
        });

        ClassInstruct.setText("Classroom Instruction");
        ClassInstruct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClassInstructActionPerformed(evt);
            }
        });

        IndividualStudentAdvising.setText("Individual Student Advising");
        IndividualStudentAdvising.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IndividualStudentAdvisingActionPerformed(evt);
            }
        });

        ChildProtect.setText("Child Protection Interviews");
        ChildProtect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChildProtectActionPerformed(evt);
            }
        });

        TestInterpret.setText("Test Interpretation");
        TestInterpret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TestInterpretActionPerformed(evt);
            }
        });

        NewStudentOrient.setText("New Student Orientation Meetings");
        NewStudentOrient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewStudentOrientActionPerformed(evt);
            }
        });

        ParentTeacherMeetings.setText("Parent/Teacher Meetings With Student");
        ParentTeacherMeetings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParentTeacherMeetingsActionPerformed(evt);
            }
        });

        Stopwatch.setText("Stopwatch");
        Stopwatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopwatchActionPerformed(evt);
            }
        });

        CalculateMainActivityGroup.setText("Calculate Hours Spent for Main Activity Group");
        CalculateMainActivityGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateMainActivityGroupActionPerformed(evt);
            }
        });

        CalculateSubActivityGroup.setText("Calculate Hours Spent for Sub Activity Group");
        CalculateSubActivityGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateSubActivityGroupActionPerformed(evt);
            }
        });

        Closewindow.setText("Close Window");
        Closewindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClosewindowActionPerformed(evt);
            }
        });

        jTextField2.setText("Select an Activity Sub Category");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Stopwatch)
                .addGap(92, 92, 92))
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SmallGroupCounsel)
                    .addComponent(IndividualCounsel)
                    .addComponent(IndividualStudentAdvising)
                    .addComponent(ClassInstruct)
                    .addComponent(CalculateMainActivityGroup)
                    .addComponent(CalculateSubActivityGroup))
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TestInterpret, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NewStudentOrient, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ChildProtect, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ParentTeacherMeetings, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(Closewindow)
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Closewindow)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IndividualCounsel)
                    .addComponent(ParentTeacherMeetings))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SmallGroupCounsel)
                    .addComponent(TestInterpret))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IndividualStudentAdvising)
                    .addComponent(ChildProtect))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewStudentOrient)
                    .addComponent(ClassInstruct))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Stopwatch)
                    .addComponent(CalculateMainActivityGroup))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CalculateSubActivityGroup))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TestInterpretActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TestInterpretActionPerformed
        activitySub = "Test Interpretation";
    }//GEN-LAST:event_TestInterpretActionPerformed

    private void IndividualCounselActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IndividualCounselActionPerformed
        activitySub = "Individual Counseling";
    }//GEN-LAST:event_IndividualCounselActionPerformed

    private void SmallGroupCounselActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SmallGroupCounselActionPerformed
        activitySub = "Small Group Counseling";
    }//GEN-LAST:event_SmallGroupCounselActionPerformed

    private void IndividualStudentAdvisingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IndividualStudentAdvisingActionPerformed
       activitySub = "Individual Student Advising";
    }//GEN-LAST:event_IndividualStudentAdvisingActionPerformed

    private void ClassInstructActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClassInstructActionPerformed
       activitySub = "Class Instruction";
    }//GEN-LAST:event_ClassInstructActionPerformed

    private void ParentTeacherMeetingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParentTeacherMeetingsActionPerformed
       activitySub = "Parent Teacher Meetings With Students";
    }//GEN-LAST:event_ParentTeacherMeetingsActionPerformed

    private void ChildProtectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChildProtectActionPerformed
       activitySub = "Child Protection Interviews";
    }//GEN-LAST:event_ChildProtectActionPerformed

    private void NewStudentOrientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewStudentOrientActionPerformed
       activitySub = "New Student Orientation Meetings";
    }//GEN-LAST:event_NewStudentOrientActionPerformed

    private void StopwatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopwatchActionPerformed
        Stopwatch Stopwatch1 = new Stopwatch();
        Stopwatch1.setVisible(true);
        Stopwatch1.setactivityMain("Direct Student Services");
        Stopwatch1.setactivitySub(activitySub);
    }//GEN-LAST:event_StopwatchActionPerformed

    private void CalculateMainActivityGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateMainActivityGroupActionPerformed
        Calculator Calculator = new Calculator();//opens calculator class for jFrame
        Calculator.setVisible(true);
        Calculator.setactivityMainSelect("Direct Student Services");
    }//GEN-LAST:event_CalculateMainActivityGroupActionPerformed

    private void CalculateSubActivityGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateSubActivityGroupActionPerformed
        Calculator Calculator2 = new Calculator();//opens calculator class for sub activities jFrame
        Calculator2.setVisible(true);
        Calculator2.setactivitySubSelect(activitySub);
    }//GEN-LAST:event_CalculateSubActivityGroupActionPerformed

    private void ClosewindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClosewindowActionPerformed
        //IndirectStudentServices.dispose();
    }//GEN-LAST:event_ClosewindowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DirectStudentServices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DirectStudentServices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DirectStudentServices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DirectStudentServices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DirectStudentServices().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CalculateMainActivityGroup;
    private javax.swing.JButton CalculateSubActivityGroup;
    private javax.swing.JRadioButton ChildProtect;
    private javax.swing.JRadioButton ClassInstruct;
    private javax.swing.JButton Closewindow;
    private javax.swing.JRadioButton IndividualCounsel;
    private javax.swing.JRadioButton IndividualStudentAdvising;
    private javax.swing.JRadioButton NewStudentOrient;
    private javax.swing.JRadioButton ParentTeacherMeetings;
    private javax.swing.JRadioButton SmallGroupCounsel;
    private javax.swing.JButton Stopwatch;
    private javax.swing.JRadioButton TestInterpret;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
