/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 * Remember to work on Save Button!!!!!!!!!!!!!! (important)
 */
package counsellorapp;


/**
 *
 * @author sohumsanjaythadani
 */
public class IndirectStudentServices extends javax.swing.JFrame implements Runnable {
    
    String activityMain = "Indirect Student Services";
    String activitySub;

    /**
     * Creates new form IndirectStudentServices
     */
    public IndirectStudentServices() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ParentMeetings = new javax.swing.JRadioButton();
        CollegeRepVisits = new javax.swing.JRadioButton();
        ParentTeacherConferences = new javax.swing.JRadioButton();
        SSTMeetings = new javax.swing.JRadioButton();
        ClassroomObservations = new javax.swing.JRadioButton();
        jTextField2 = new javax.swing.JTextField();
        Stopwatch = new javax.swing.JButton();
        Refferall = new javax.swing.JRadioButton();
        CalculateHourSpentMain = new javax.swing.JButton();
        CalculateHourSpentSub = new javax.swing.JButton();
        Closewindow = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ParentMeetings.setText("Parent meetings");
        ParentMeetings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParentMeetingsActionPerformed(evt);
            }
        });

        CollegeRepVisits.setText("College Rep Visits");
        CollegeRepVisits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CollegeRepVisitsActionPerformed(evt);
            }
        });

        ParentTeacherConferences.setText("Parent/Teacher conferences without students");
        ParentTeacherConferences.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParentTeacherConferencesActionPerformed(evt);
            }
        });

        SSTMeetings.setText("SST meetings");
        SSTMeetings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SSTMeetingsActionPerformed(evt);
            }
        });

        ClassroomObservations.setText("Classroom Observations");
        ClassroomObservations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClassroomObservationsActionPerformed(evt);
            }
        });

        jTextField2.setText("Select an Activity Sub Category");

        Stopwatch.setText("Stopwatch");
        Stopwatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopwatchActionPerformed(evt);
            }
        });

        Refferall.setText("Refferral");
        Refferall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefferallActionPerformed(evt);
            }
        });

        CalculateHourSpentMain.setText("Calculate Hours Spent for Main Activity Group");
        CalculateHourSpentMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateHourSpentMainActionPerformed(evt);
            }
        });

        CalculateHourSpentSub.setText("Calculate Hours Spent for Sub Activity Group");
        CalculateHourSpentSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateHourSpentSubActionPerformed(evt);
            }
        });

        Closewindow.setText("Close Window");
        Closewindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClosewindowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CalculateHourSpentMain)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(CalculateHourSpentSub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(33, 33, 33)
                        .addComponent(Stopwatch))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Refferall)
                            .addComponent(ParentMeetings))
                        .addGap(131, 131, 131)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ClassroomObservations)
                            .addComponent(CollegeRepVisits)))
                    .addComponent(ParentTeacherConferences)
                    .addComponent(SSTMeetings))
                .addContainerGap(111, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Closewindow)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Closewindow))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CollegeRepVisits)
                    .addComponent(Refferall))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ParentMeetings)
                    .addComponent(ClassroomObservations, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ParentTeacherConferences)
                .addGap(18, 18, 18)
                .addComponent(SSTMeetings)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(Stopwatch)
                        .addGap(41, 41, 41))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(CalculateHourSpentMain)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CalculateHourSpentSub)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StopwatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopwatchActionPerformed
        Stopwatch Stopwatch1 = new Stopwatch();
        Stopwatch1.setVisible(true);
        Stopwatch1.setactivityMain("Indirect Student Services");
        Stopwatch1.setactivitySub(activitySub);
    }//GEN-LAST:event_StopwatchActionPerformed

    private void RefferallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefferallActionPerformed
        activitySub= "Refferall";
// enter sub activities
    }//GEN-LAST:event_RefferallActionPerformed

    private void ParentMeetingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParentMeetingsActionPerformed
        activitySub= "Classrrom Observation";
    }//GEN-LAST:event_ParentMeetingsActionPerformed

    private void ParentTeacherConferencesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParentTeacherConferencesActionPerformed
        activitySub = "Parent Meetings";
    }//GEN-LAST:event_ParentTeacherConferencesActionPerformed

    private void SSTMeetingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SSTMeetingsActionPerformed
        activitySub= "Parent/Teacher Conferences Without Students";
    }//GEN-LAST:event_SSTMeetingsActionPerformed

    private void CollegeRepVisitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CollegeRepVisitsActionPerformed
        activitySub = "SST Meetings";
    }//GEN-LAST:event_CollegeRepVisitsActionPerformed

    private void ClassroomObservationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClassroomObservationsActionPerformed
        activitySub = "College Rep Visits";
    }//GEN-LAST:event_ClassroomObservationsActionPerformed

    private void CalculateHourSpentMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateHourSpentMainActionPerformed
        Calculator Calculator = new Calculator();//opens calculator class for jFrame
        Calculator.setVisible(true);
        Calculator.setactivityMainSelect("Indirect Student Services");
        //listCopy.calculateactivitymainSum("Indirect Student Services");
        //Calculator.setactivitySubSelect(activitySub);
    }//GEN-LAST:event_CalculateHourSpentMainActionPerformed

    private void CalculateHourSpentSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateHourSpentSubActionPerformed
         Calculator Calculator2 = new Calculator();//opens calculator class for sub activities jFrame
         Calculator2.setVisible(true);
         Calculator2.setactivitySubSelect(activitySub);
    }//GEN-LAST:event_CalculateHourSpentSubActionPerformed

    private void ClosewindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClosewindowActionPerformed
        //IndirectStudentServices.dispose();
    }//GEN-LAST:event_ClosewindowActionPerformed


    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IndirectStudentServices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IndirectStudentServices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IndirectStudentServices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IndirectStudentServices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            IndirectStudentServices subMenu1 = new IndirectStudentServices();
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CalculateHourSpentMain;
    private javax.swing.JButton CalculateHourSpentSub;
    private javax.swing.JRadioButton ClassroomObservations;
    private javax.swing.JButton Closewindow;
    private javax.swing.JRadioButton CollegeRepVisits;
    private javax.swing.JRadioButton ParentMeetings;
    private javax.swing.JRadioButton ParentTeacherConferences;
    private javax.swing.JRadioButton Refferall;
    private javax.swing.JRadioButton SSTMeetings;
    private javax.swing.JButton Stopwatch;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
