/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package counsellorapp;

/**
 *
 * @author sohumsanjaythadani
 */
public class NonSchoolCounsellingTasks extends javax.swing.JFrame {
    String activityMain = "Non-School Counseling Tasks";
    String activitySub;

    /**
     * Creates new form NonSchoolCounsellingTasks
     */
    public NonSchoolCounsellingTasks() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Closewindow = new javax.swing.JButton();
        CoverClassrooms = new javax.swing.JRadioButton();
        PSATandSAT = new javax.swing.JRadioButton();
        Admissions = new javax.swing.JRadioButton();
        Duty = new javax.swing.JRadioButton();
        Discipline = new javax.swing.JRadioButton();
        ChaperoningEvents = new javax.swing.JRadioButton();
        ChinaTrips = new javax.swing.JRadioButton();
        MasterSchedule = new javax.swing.JRadioButton();
        CalculateHourSpentMain = new javax.swing.JButton();
        CalculateHourSpentSub = new javax.swing.JButton();
        Stopwatch = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Closewindow.setText("Close Window");
        Closewindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClosewindowActionPerformed(evt);
            }
        });

        CoverClassrooms.setText("Covering Classrooms");
        CoverClassrooms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoverClassroomsActionPerformed(evt);
            }
        });

        PSATandSAT.setText("PSAT/SAT Organization");
        PSATandSAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PSATandSATActionPerformed(evt);
            }
        });

        Admissions.setText("Admissions ");
        Admissions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdmissionsActionPerformed(evt);
            }
        });

        Duty.setText("Lunch & After-School Duty");
        Duty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DutyActionPerformed(evt);
            }
        });

        Discipline.setText("Discipline ");
        Discipline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisciplineActionPerformed(evt);
            }
        });

        ChaperoningEvents.setText("Chaperoning Events");
        ChaperoningEvents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChaperoningEventsActionPerformed(evt);
            }
        });

        ChinaTrips.setText("China Trips");
        ChinaTrips.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChinaTripsActionPerformed(evt);
            }
        });

        MasterSchedule.setText("Building Master Schedule");
        MasterSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasterScheduleActionPerformed(evt);
            }
        });

        CalculateHourSpentMain.setText("Calculate Hours Spent for Main Activity Group");
        CalculateHourSpentMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateHourSpentMainActionPerformed(evt);
            }
        });

        CalculateHourSpentSub.setText("Calculate Hours Spent for Sub Activity Group");
        CalculateHourSpentSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateHourSpentSubActionPerformed(evt);
            }
        });

        Stopwatch.setText("Stopwatch");
        Stopwatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopwatchActionPerformed(evt);
            }
        });

        jTextField2.setText("Select an Activity Sub Category");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103)
                .addComponent(Closewindow)
                .addGap(36, 36, 36))
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CoverClassrooms)
                    .addComponent(Duty)
                    .addComponent(Admissions)
                    .addComponent(PSATandSAT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Discipline)
                    .addComponent(ChaperoningEvents)
                    .addComponent(ChinaTrips)
                    .addComponent(MasterSchedule))
                .addGap(152, 152, 152))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CalculateHourSpentSub)
                    .addComponent(CalculateHourSpentMain))
                .addGap(76, 76, 76)
                .addComponent(Stopwatch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Closewindow)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CoverClassrooms)
                    .addComponent(Discipline))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PSATandSAT)
                    .addComponent(ChaperoningEvents))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Admissions)
                    .addComponent(ChinaTrips))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Duty)
                            .addComponent(MasterSchedule))
                        .addGap(42, 42, 42)
                        .addComponent(CalculateHourSpentMain)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CalculateHourSpentSub)
                        .addContainerGap(21, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Stopwatch)
                        .addGap(43, 43, 43))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClosewindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClosewindowActionPerformed
        //IndirectStudentServices.dispose();
    }//GEN-LAST:event_ClosewindowActionPerformed

    private void PSATandSATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PSATandSATActionPerformed
        activitySub= "PSAT & SAT Organization";
    }//GEN-LAST:event_PSATandSATActionPerformed

    private void CalculateHourSpentMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateHourSpentMainActionPerformed
        Calculator Calculator = new Calculator();//opens calculator class for jFrame
        Calculator.setVisible(true);
        Calculator.setactivityMainSelect("Indirect Student Services");
        //listCopy.calculateactivitymainSum("Indirect Student Services");
        //Calculator.setactivitySubSelect(activitySub);
    }//GEN-LAST:event_CalculateHourSpentMainActionPerformed

    private void CalculateHourSpentSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateHourSpentSubActionPerformed
        Calculator Calculator2 = new Calculator();//opens calculator class for sub activities jFrame
        Calculator2.setVisible(true);
        Calculator2.setactivitySubSelect(activitySub);
    }//GEN-LAST:event_CalculateHourSpentSubActionPerformed

    private void StopwatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopwatchActionPerformed
        Stopwatch Stopwatch1 = new Stopwatch();
        Stopwatch1.setVisible(true);
        Stopwatch1.setactivityMain("Indirect Student Services");
        Stopwatch1.setactivitySub(activitySub);
    }//GEN-LAST:event_StopwatchActionPerformed

    private void CoverClassroomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoverClassroomsActionPerformed
        activitySub= "Cover Classrooms";
    }//GEN-LAST:event_CoverClassroomsActionPerformed

    private void AdmissionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdmissionsActionPerformed
       activitySub= "Admissions";
    }//GEN-LAST:event_AdmissionsActionPerformed

    private void DutyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DutyActionPerformed
        activitySub= "Lunch and Afterschool Duty";
    }//GEN-LAST:event_DutyActionPerformed

    private void DisciplineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisciplineActionPerformed
        activitySub= "Discipline";
    }//GEN-LAST:event_DisciplineActionPerformed

    private void ChaperoningEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChaperoningEventsActionPerformed
        activitySub= "Chaperoning Events";
    }//GEN-LAST:event_ChaperoningEventsActionPerformed

    private void ChinaTripsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChinaTripsActionPerformed
       activitySub= "China Trips";
    }//GEN-LAST:event_ChinaTripsActionPerformed

    private void MasterScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasterScheduleActionPerformed
        activitySub = "Plan Master Schedule";
    }//GEN-LAST:event_MasterScheduleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NonSchoolCounsellingTasks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NonSchoolCounsellingTasks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NonSchoolCounsellingTasks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NonSchoolCounsellingTasks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NonSchoolCounsellingTasks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Admissions;
    private javax.swing.JButton CalculateHourSpentMain;
    private javax.swing.JButton CalculateHourSpentSub;
    private javax.swing.JRadioButton ChaperoningEvents;
    private javax.swing.JRadioButton ChinaTrips;
    private javax.swing.JButton Closewindow;
    private javax.swing.JRadioButton CoverClassrooms;
    private javax.swing.JRadioButton Discipline;
    private javax.swing.JRadioButton Duty;
    private javax.swing.JRadioButton MasterSchedule;
    private javax.swing.JRadioButton PSATandSAT;
    private javax.swing.JButton Stopwatch;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
