/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package counsellorapp;

/**
 *
 * @author sohumsanjaythadani
 */
public class Other extends javax.swing.JFrame {

    String activityMain= "other";
    String activitySub;
    /**
     * Creates new form Other
     */
    public Other() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Stopwatch = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        CalculateMainActivityGroup = new javax.swing.JButton();
        CalculateSubActivityGroup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Stopwatch.setText("Stopwatch");
        Stopwatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopwatchActionPerformed(evt);
            }
        });

        jTextField3.setText("Other Category");

        CalculateMainActivityGroup.setText("Calculate Hours Spent for Main Activity Group");
        CalculateMainActivityGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateMainActivityGroupActionPerformed(evt);
            }
        });

        CalculateSubActivityGroup.setText("Calculate Hours Spent for Sub Activity Group");
        CalculateSubActivityGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateSubActivityGroupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Stopwatch)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CalculateSubActivityGroup)
                            .addComponent(CalculateMainActivityGroup))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(Stopwatch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CalculateMainActivityGroup)
                .addGap(18, 18, 18)
                .addComponent(CalculateSubActivityGroup)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StopwatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopwatchActionPerformed
        Stopwatch Stopwatch1 = new Stopwatch();
        Stopwatch1.setVisible(true);
        Stopwatch1.setactivityMain("Indirect Student Services");
        Stopwatch1.setactivitySub(activitySub);
    }//GEN-LAST:event_StopwatchActionPerformed

    private void CalculateMainActivityGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateMainActivityGroupActionPerformed
        Calculator Calculator = new Calculator();//opens calculator class for jFrame
        Calculator.setVisible(true);
        Calculator.setactivityMainSelect("Direct Student Services");
    }//GEN-LAST:event_CalculateMainActivityGroupActionPerformed

    private void CalculateSubActivityGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateSubActivityGroupActionPerformed
        Calculator Calculator2 = new Calculator();//opens calculator class for sub activities jFrame
        Calculator2.setVisible(true);
        Calculator2.setactivitySubSelect(activitySub);
    }//GEN-LAST:event_CalculateSubActivityGroupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Other.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Other.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Other.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Other.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Other().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CalculateMainActivityGroup;
    private javax.swing.JButton CalculateSubActivityGroup;
    private javax.swing.JButton Stopwatch;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
