/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package counsellorapp;

/**
 *
 * @author sohumsanjaythadani
 */
public class ProgramDefiningManaging extends javax.swing.JFrame {

    String activityMain = "Program Defining, Managing & Assesing";
    String activitySub;

    public ProgramDefiningManaging() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        Closewindow2 = new javax.swing.JButton();
        BuildSchoolCurric = new javax.swing.JRadioButton();
        ReviewData = new javax.swing.JRadioButton();
        ProffDevelopment = new javax.swing.JRadioButton();
        FairShareResponsibilities = new javax.swing.JRadioButton();
        ChildProtectionProcessMeet = new javax.swing.JRadioButton();
        DepartmentMeetings = new javax.swing.JRadioButton();
        ParentCoffeePresentations = new javax.swing.JRadioButton();
        CalculateHoursSpentforSubActivites = new javax.swing.JButton();
        Stopwatch = new javax.swing.JButton();
        CalculateHoursSpentMainActivity1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField3.setText("Select an Activity Sub Category");

        Closewindow2.setText("Close Window");
        Closewindow2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Closewindow2ActionPerformed(evt);
            }
        });

        BuildSchoolCurric.setText("Build School-Wide Counseling Curriculum");
        BuildSchoolCurric.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuildSchoolCurricActionPerformed(evt);
            }
        });

        ReviewData.setText("Review Data");
        ReviewData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReviewDataActionPerformed(evt);
            }
        });

        ProffDevelopment.setText("Professional Development");
        ProffDevelopment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProffDevelopmentActionPerformed(evt);
            }
        });

        FairShareResponsibilities.setText("Fair-Share Responsibilities");
        FairShareResponsibilities.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FairShareResponsibilitiesActionPerformed(evt);
            }
        });

        ChildProtectionProcessMeet.setText("Child Protection Process Meetings");
        ChildProtectionProcessMeet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChildProtectionProcessMeetActionPerformed(evt);
            }
        });

        DepartmentMeetings.setText("Department Meetings ");
        DepartmentMeetings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepartmentMeetingsActionPerformed(evt);
            }
        });

        ParentCoffeePresentations.setText("Parent Coffee Presentations");
        ParentCoffeePresentations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParentCoffeePresentationsActionPerformed(evt);
            }
        });

        CalculateHoursSpentforSubActivites.setText("Calculate Hours Spent for Sub Activity Group");
        CalculateHoursSpentforSubActivites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateHoursSpentforSubActivitesActionPerformed(evt);
            }
        });

        Stopwatch.setText("Stopwatch");
        Stopwatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopwatchActionPerformed(evt);
            }
        });

        CalculateHoursSpentMainActivity1.setText("Calculate Hours Spent for Main Activity Group");
        CalculateHoursSpentMainActivity1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateHoursSpentMainActivity1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ParentCoffeePresentations)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BuildSchoolCurric)
                            .addComponent(ReviewData)
                            .addComponent(ProffDevelopment))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DepartmentMeetings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FairShareResponsibilities, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ChildProtectionProcessMeet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(55, 55, 55))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(Closewindow2)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CalculateHoursSpentMainActivity1)
                    .addComponent(CalculateHoursSpentforSubActivites))
                .addGap(58, 58, 58)
                .addComponent(Stopwatch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Closewindow2))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReviewData)
                    .addComponent(ChildProtectionProcessMeet))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BuildSchoolCurric)
                    .addComponent(DepartmentMeetings))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProffDevelopment, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FairShareResponsibilities))
                .addGap(18, 18, 18)
                .addComponent(ParentCoffeePresentations)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(CalculateHoursSpentMainActivity1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CalculateHoursSpentforSubActivites, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Stopwatch)
                        .addGap(32, 32, 32))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Closewindow2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Closewindow2ActionPerformed
        //IndirectStudentServices.dispose();
    }//GEN-LAST:event_Closewindow2ActionPerformed

    private void StopwatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopwatchActionPerformed
        Stopwatch Stopwatch1 = new Stopwatch();
        Stopwatch1.setVisible(true);
        Stopwatch1.setactivityMain("Program Defining, Managing & Assesing");
        Stopwatch1.setactivitySub(activitySub);
    }//GEN-LAST:event_StopwatchActionPerformed

    private void CalculateHoursSpentMainActivity1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateHoursSpentMainActivity1ActionPerformed
        Calculator Calculator = new Calculator();//opens calculator class for jFrame
        Calculator.setVisible(true);
        Calculator.setactivityMainSelect("Program Defining, Managing & Assesing");
    }//GEN-LAST:event_CalculateHoursSpentMainActivity1ActionPerformed

    private void CalculateHoursSpentforSubActivitesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateHoursSpentforSubActivitesActionPerformed
        Calculator Calculator2 = new Calculator();//opens calculator class for sub activities jFrame
        Calculator2.setVisible(true);
        Calculator2.setactivitySubSelect(activitySub);
    }//GEN-LAST:event_CalculateHoursSpentforSubActivitesActionPerformed

    private void ReviewDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReviewDataActionPerformed
        activitySub = "Review Data";
    }//GEN-LAST:event_ReviewDataActionPerformed

    private void BuildSchoolCurricActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuildSchoolCurricActionPerformed
        activitySub = "Build School-Wide Counseling Curriculum";
    }//GEN-LAST:event_BuildSchoolCurricActionPerformed

    private void ProffDevelopmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProffDevelopmentActionPerformed
        activitySub = "Professional Development";
    }//GEN-LAST:event_ProffDevelopmentActionPerformed

    private void ParentCoffeePresentationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParentCoffeePresentationsActionPerformed
        activitySub = "Parent Coffee Presentations";
    }//GEN-LAST:event_ParentCoffeePresentationsActionPerformed

    private void ChildProtectionProcessMeetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChildProtectionProcessMeetActionPerformed
        activitySub = "Child Protection Process Meetings";
    }//GEN-LAST:event_ChildProtectionProcessMeetActionPerformed

    private void DepartmentMeetingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepartmentMeetingsActionPerformed
        activitySub = "Department Meetings";
    }//GEN-LAST:event_DepartmentMeetingsActionPerformed

    private void FairShareResponsibilitiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FairShareResponsibilitiesActionPerformed
        activitySub = "Fair-Share Responsibilites ";
    }//GEN-LAST:event_FairShareResponsibilitiesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProgramDefiningManaging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProgramDefiningManaging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProgramDefiningManaging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProgramDefiningManaging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProgramDefiningManaging().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BuildSchoolCurric;
    private javax.swing.JButton CalculateHoursSpentMainActivity1;
    private javax.swing.JButton CalculateHoursSpentforSubActivites;
    private javax.swing.JRadioButton ChildProtectionProcessMeet;
    private javax.swing.JButton Closewindow;
    private javax.swing.JButton Closewindow1;
    private javax.swing.JButton Closewindow2;
    private javax.swing.JRadioButton DepartmentMeetings;
    private javax.swing.JRadioButton FairShareResponsibilities;
    private javax.swing.JRadioButton ParentCoffeePresentations;
    private javax.swing.JRadioButton ProffDevelopment;
    private javax.swing.JRadioButton ReviewData;
    private javax.swing.JButton Stopwatch;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
